### ISSUE TITLE
Forum Integration 

### ISSUE THREAD

**Issue by werdes** [QuagganBooOOoot/gitter-bot#3]
Post forum contents when somebody posts a link.
probably steal (borrow) some logic from polarbytebot (https://github.com/networkjanitor/polarbytebot)

**Comment by darthmaim** [comment]
Additionally write a message to chat when a new forum thread is created (this can work with the new forum api). See [gitter](https://gitter.im/arenanet/api-cdi?at=59b83db8614889d475ed5797).
